package com.punchyepicfightcompat.client.config;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Small, deliberately strict TOML reader for the generated animation map.
 * Keeping it separate from ForgeConfigSpec allows animation IDs discovered at
 * runtime to become real boolean keys without rebuilding a fixed config spec.
 */
public final class AnimationPreferenceFile {
    private static final Pattern SECTION = Pattern.compile("^\\s*\\[([^]]+)]\\s*(?:#.*)?$");
    private static final Pattern ENTRY = Pattern.compile(
        "^\\s*\"((?:\\\\.|[^\"\\\\])*)\"\\s*=\\s*(true|false)\\s*(?:#.*)?$",
        Pattern.CASE_INSENSITIVE
    );

    private AnimationPreferenceFile() {}

    public static ReadResult read(Path path) throws IOException {
        if (!Files.isRegularFile(path)) {
            return new ReadResult(new LinkedHashMap<>(), List.of());
        }

        Map<String, Boolean> values = new LinkedHashMap<>();
        List<String> invalidLines = new ArrayList<>();
        boolean inAnimations = false;
        int lineNumber = 0;

        for (String line : Files.readAllLines(path, StandardCharsets.UTF_8)) {
            lineNumber++;
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#")) {
                continue;
            }

            Matcher sectionMatcher = SECTION.matcher(line);
            if (sectionMatcher.matches()) {
                inAnimations = "animations".equals(sectionMatcher.group(1).trim());
                continue;
            }

            if (!inAnimations) {
                continue;
            }

            Matcher entryMatcher = ENTRY.matcher(line);
            if (!entryMatcher.matches()) {
                invalidLines.add("line " + lineNumber + ": " + trimmed);
                continue;
            }

            String key;
            try {
                key = unescape(entryMatcher.group(1));
            } catch (IllegalArgumentException exception) {
                invalidLines.add("line " + lineNumber + ": " + trimmed);
                continue;
            }
            values.put(key, Boolean.parseBoolean(entryMatcher.group(2)));
        }

        return new ReadResult(values, invalidLines);
    }

    public static void write(Path path, Map<String, Boolean> values) throws IOException {
        Path parent = path.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        StringBuilder output = new StringBuilder(4096);
        output.append("# Generated by Punchy x Epic Fight Compatibility.\n")
            .append("# true  = show Epic Fight's first-person body for this animation.\n")
            .append("# false = force Punchy for this animation, even while holding a sword.\n")
            .append("# Existing choices are preserved; newly registered animations are added automatically.\n\n")
            .append("[animations]\n");

        values.entrySet().stream()
            .sorted(Map.Entry.comparingByKey())
            .forEach(entry -> output
                .append('"').append(escape(entry.getKey())).append("\" = ")
                .append(entry.getValue()).append('\n'));

        Path temporary = path.resolveSibling(path.getFileName() + ".tmp");
        Files.writeString(temporary, output.toString(), StandardCharsets.UTF_8);
        try {
            Files.move(temporary, path, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
        } catch (IOException atomicMoveFailure) {
            Files.move(temporary, path, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    static String escape(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    static String unescape(String value) {
        StringBuilder result = new StringBuilder(value.length());
        boolean escaped = false;
        for (int index = 0; index < value.length(); index++) {
            char character = value.charAt(index);
            if (escaped) {
                if (character != '\\' && character != '"') {
                    throw new IllegalArgumentException("Unsupported escape sequence");
                }
                result.append(character);
                escaped = false;
            } else if (character == '\\') {
                escaped = true;
            } else {
                result.append(character);
            }
        }
        if (escaped) {
            throw new IllegalArgumentException("Incomplete escape sequence");
        }
        return result.toString();
    }

    public record ReadResult(Map<String, Boolean> values, List<String> invalidLines) {}
}
